### ISSUE TITLE
Test Pipeline Building  

### ISSUE THREAD

**Issue by lsjtop10** [Goboolean/core-system.worker#102]
# 목표

config.test.yml을 기반으로 다음 항목을 검증
1. config.test.yml이 application configuration 객체로 잘 파싱되는지
2. 파싱된 configuration 객체로 pipeline.Build()에서 job별 spec이 잘 추출되는지
3. 추출된 spec을 바탕으로 올바른 job이 {jobs}.Create()함수에서 생성되는지
4. 생성된 job이 올바른 pipeline에 잘 주입되는지
5. Pipeline에서 job들이 잘 연결돼서 서로 데이터 잘 주고받는지
6. 데이터가 올바른 방향으로 pipeline 안에서 흐르는지

# TODO

- [x] config.test.yml 작성
- [x] #101 
- [x] transmitter 인프라 모킹
- [x] pipeline 자동화 test 작성

**Comment by lsjtop10** [comment]
1, 2, 3, 4 항목은 Builder에서 테스트
5,6은 각각 파이프라인에서 테스트하기로 결정됐습니다.

**Comment by lsjtop10** [comment]
#106

**Comment by lsjtop10** [comment]
#109 참조

**Comment by lsjtop10** [comment]
이번 이슈는 닫고 나머지 작업은 #109에서 이어서 합니다.
